### ISSUE TITLE
Fix echart error

### ISSUE THREAD

**Issue by frano-m** [anvilproject/anvil-portal#2164]
On leaving the page https://staging.anvilproject.org/overview/data-consortia, an echart error prevents page rendering.

```
TypeError: Cannot read properties of null (reading 'off')
    at e.off (zrender.js:246:18)
    at Ek.v.createElement.ref (data-ingestion-chart.tsx:251:22)
    at ei (react-dom.production.min.js:240:251)
    at ni (react-dom.production.min.js:244:163)
    at Ss (react-dom.production.min.js:284:388)
    at is (react-dom.production.min.js:273:185)
    at Aa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at ws (react-dom.production.min.js:281:398)
    at as (react-dom.production.min.js:270:269)
```

**Comment by NoopDog** [comment]
Done!
